version: "3.3"

services: 
    db:
        image: mysql
        volumes:
            - ./MySQL:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=root
        restart: always  
        ports:
            - 3306:3306
    server:
        build: .
        volumes:
            - ./Server.py:/var/site/Server.py
            - ./Templates/:/var/site/templates/
            - ./static/:/var/site/static/
            - ./TLSKeys/:/var/site/TLSKeys/
        ports:
            - "5000:5000"
            - "8001:8001"
        command: python3 /var/site/Server.py
        depends_on:
            - db
    prometheus:
        image: prom/prometheus
        volumes:
            - ./prometheus:/etc/prometheus
           # - ./prometheus/data:/data/prometheus
        ports:
            - 9090:9090
        command:  
            --config.file=/etc/prometheus/prometheus.yml
        restart: always
        depends_on:
            - server
    grafana:
        image: grafana/grafana
        restart: always
        volumes:
            - ./grafana:/var/lib/grafana
        ports: 
            - 3000:3000
        depends_on:
            - prometheus
    node_exporter:
        image: prom/node-exporter
        ports:
            - 9100:9100
    