version: "3.3"

services: 
    db:
        image: mysql
        volumes:
            - ./MySQL:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=root
        restart: always  
        ports:
            - 3306:3306
    server:
        build: .
        volumes:
            - ./Server.py:/var/site/Server.py
            - ./Templates/:/var/site/templates/
            - ./static/:/var/site/static/
        ports:
            - 5000:5000
        command: python3 /var/site/Server.py
        depends_on:
            - db
    prometheus:
        image: prom/prometheus
        volumes:
            - ./prometheus:/etc/prometheus
            - ./prometheus/data:/data/prometheus
        ports:
            - 9090:9090
        command:  
            --config.file=/etc/prometheus/prometheus.yml
            #--storage.tsdb.path=/data/prometheus
        restart: always
        depends_on:
            - server
    grafana:
        image: grafana/grafana
        restart: always
        volumes:
            - ./grafana:/var/lib/grafana
        ports: 
            - 3000:3000
        depends_on:
            - prometheus
    node_exporter: #https://github.com/stefanprodan/dockprom/blob/master/docker-compose.yml
        image: quay.io/prometheus/node-exporter:latest
        ports:
            - 9100:9100
        restart: always
        #network_mode: host
        pid: host
        volumes:
            - /:/host:ro
        command:
            - '--path.rootfs=/host'
        depends_on:
            - grafana

#networks:
#    nett:
#        driver: bridge
    

    